#!/bin/bash

## Show Help if no option is passed through
if [ -z "$1" ]
	then
		echo "Borgrestore https://github.com/solisinvictum/borgrestore"
		echo ""
		echo "Options:"
		echo "  -h This Help output"
		echo "  -u Update Borgrestore"
		echo "  -r Restore Snapshot"
		echo ""
		exit
fi

## The Help if -h passed through
if [ "$1" = "-h" ]
then
		echo "Borgrestore https://github.com/solisinvictum/borgrestore"
		echo ""
		echo "Options:"
		echo "  -h This Help output"
		echo "  -u Update Borgrestore"
		echo "  -r Restore Snapshot"
		echo ""
		exit
fi

## If requested, this updates borgrestore and exits
if [ "$1" = "-u" ]
then
		if [ "$EUID" -ne 0 ]
		then 
				echo "To update borgrestore, you need to be root"
				exit
		fi

		wget -q https://raw.githubusercontent.com/solisinvictum/borgrestore/main/borgrestore -O /usr/bin/borgrestore &> /dev/null
		echo "Borgrestore was updated to the last commits from github page"
		echo "see https://github.com/solisinvictum/borgrestore/commits/main/borgrestore what is new"
		exit
		
fi

## if -r for actualy start borgrestore is choosen, start borgrestore's actualy purporse :-)
if [ "$1" = "-r" ]
then

## Include the Configfile
source "/etc/borgrestore/borgrestore.conf"

## Check if the Configfile was readed and configured
if [ $CONFIGURED = "0" ]
    then

       echo "Please read and configure the configfile under /etc/borgrestore/borgrestore.conf first!"
       exit
fi

## Mounts the Repo
borg mount "$BORGREPO" "$MOUNTPOINT"

echo "------------------------------------------"
echo "Wich Snapshot do you want to restore? If you took this Snapshot with Vorta, then the Syntax would be hostname-year-mounth-day-time, for my Machine galaxias-2021-11-23-212617 for example"
echo "------------------------------------------"

## Lists what Snapshots are available from Borg and ask wich one to restore
mapfile -t array < <(borg list --short "$BORGREPO")

PS3="Selection: "
select snapshot in "${array[@]}"
do

	if [[ -z "$snapshot" ]]
	then
		echo "Wrong Input!"
	else
		echo ""
		echo "Selected: $snapshot"
		echo ""
		break
	fi
done
PS3="#?"

## Customized Whileloop from this Source because i was to lazy to read with man how loops are made: https://tecadmin.net/bash-script-prompt-to-confirm-yes-no/
while true
do
 read -r -p "ARE YOU SURE? AFTER THIS STEP, THERE IS NO WAY BACK! (y/n)" confirmation

 case $confirmation in
     [yY][eE][sS]|[yY])

        # This restores the Snapshot to Destination and at the end it prompts how long it took. This ignores borgrestore and his config himselfs too to prevent a remove/downgrade of borgrestore.
        time rsync --verbose --archive --itemize-changes --hard-links --exclude=/usr/bin/borgrestore --exclude=/etc/borgrestore/borgrestore.conf "${RSYNCEXCLUDES[@]/#/--exclude=}" --delete "$MOUNTPOINT/$snapshot/" "$DESTINATION"

        ##Realized that the deletion of the content in /tmp and /run could be wrong, if a another destination is choosen. so checking.
        if [ "$DESTINATION" = "/" ]
            then
                ## Remove some Tempfiles for a clean start from the original System (if selected). This could be unnecessary, but i like it safe.
                  if [ $LIVESYSTEM = "0" ]
                       then
                            rm -Rf -- "$DESTINATION"/tmp/*
                            rm -Rf -- "$DESTINATION"/run/*
                  fi
        fi
        ## Umount the Borg Repo again
        umount "$MOUNTPOINT"
        echo ""
        echo "------------------------------------------"
        echo "Recovery completed! System can now be restarted. If the recovery was made while the operating system was running, a reboot is mandatory!"
        echo "------------------------------------------"

 break
 ;;
     [nN][oO]|[nN])

        umount "$MOUNTPOINT"
        exit

 break
        ;;
     *)
 echo "Only Y/N are valid!"
 ;;
 esac
done

fi
